name: Build
on:
  push:
    branches:
      - 'master'
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: macos-11
    strategy:
      matrix:
        arch: [x86_64]
        platform: [macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          git clone https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-1.14.1.tar.xz
          tar -xzf xcb-proto-1.14.1.tar.xz
          cd xcb-proto-1.14.1
          echo 'PYTHON_PREFIX=@PYTHON_PREFIX@' >> xcb-proto.pc.in
          ./configure
          make
          make install
          git clone https://github.com/XQuartz/XQuartz.git
          cd XQuartz
          ./install-or-update-macports.sh
          ./compile.sh