name: Build
on:
  push:
    branches:
      - 'master'
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: macos-11
    strategy:
      matrix:
        arch: [x86_64]
        platform: [macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo mkdir -p /opt/X11/lib/pkgconfig/
          sudo chmod -R 777 /opt/X11
          export PKG_CONFIG_PATH="/opt/X11/lib/pkgconfig/"
          brew install autoconf automake pkgconfig libtool py39-mako meson xmlto asciidoc doxygen fop groff gtk-doc
          echo "::::::::::::::::::::::::::::::::::::::::::::::::"

          wget https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-1.14.1.tar.xz
          tar -xzf xcb-proto-1.14.1.tar.xz
          cd xcb-proto-1.14.1
          sed -i '' -e "5s/^//p; 5s/^.*/PYTHON_PREFIX=@PYTHON_PREFIX@/" xcb-proto.pc.in
          cat xcb-proto.pc.in
          ./configure --prefix=/opt/X11/
          make
          make install
          cd ../
          cat /opt/X11/lib/pkgconfig/xcb-proto.pc
          git clone https://github.com/XQuartz/XQuartz.git
          cd XQuartz
          ./compile.sh