name: Build
on:
  push:
    branches:
      - 'master'
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: macos-11
    strategy:
      matrix:
        arch: [x86_64]
        platform: [macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install automake
          wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.xz
          tar -xzf autoconf-2.71.tar.xz
          cd autoconf-2.71
          ./configure 
          make  
          make install
          git clone https://github.com/XQuartz/XQuartz.git
          cd XQuartz
          ./compile.sh